// <auto-generated />
using System;
using BookManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookManagement.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240124234745_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookManagement.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("author");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("genre");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("language");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("publisher");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Efrain VonRueden",
                            Genre = "Humor",
                            Language = "Fulah",
                            PublicationDate = new DateOnly(2016, 7, 7),
                            Publisher = "Grant - Frami",
                            Title = "Doloremque"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Fernando Oberbrunner",
                            Genre = "Science Fiction",
                            Language = "Upper",
                            PublicationDate = new DateOnly(2021, 2, 23),
                            Publisher = "Crist and Sons",
                            Title = "Deserunt eum"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Rey Koss",
                            Genre = "Dystopian",
                            Language = "Tibetan",
                            PublicationDate = new DateOnly(2020, 12, 1),
                            Publisher = "Zemlak and Sons",
                            Title = "Iusto facere minus"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Vito Cassin",
                            Genre = "Horror",
                            Language = "Javanese",
                            PublicationDate = new DateOnly(2015, 5, 4),
                            Publisher = "Adams, Pacocha and Marvin",
                            Title = "Ipsum"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kelsi Stehr",
                            Genre = "Technology",
                            Language = "Maithili",
                            PublicationDate = new DateOnly(2016, 4, 6),
                            Publisher = "Schamberger, Jakubowski and Murphy",
                            Title = "Qui cum"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Hiram Aufderhar",
                            Genre = "Humor",
                            Language = "Zarma",
                            PublicationDate = new DateOnly(2020, 12, 15),
                            Publisher = "Parisian, Price and Von",
                            Title = "Et"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Lexi Spinka",
                            Genre = "Thriller",
                            Language = "Nuer",
                            PublicationDate = new DateOnly(2020, 2, 27),
                            Publisher = "Stoltenberg Inc",
                            Title = "Eveniet cumque totam"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Prince Schoen",
                            Genre = "True Crime",
                            Language = "Makonde",
                            PublicationDate = new DateOnly(2022, 9, 6),
                            Publisher = "Pollich - Haag",
                            Title = "Voluptatem assumenda ut"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Corene Jones",
                            Genre = "Autobiography",
                            Language = "Chinese",
                            PublicationDate = new DateOnly(2017, 9, 29),
                            Publisher = "Streich, Harris and Haag",
                            Title = "Esse placeat quos"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Demetrius Frami",
                            Genre = "Mystery",
                            Language = "Manipuri",
                            PublicationDate = new DateOnly(2015, 11, 13),
                            Publisher = "Hahn - Champlin",
                            Title = "Aut"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Crystal Glover",
                            Genre = "Romance",
                            Language = "Bafia",
                            PublicationDate = new DateOnly(2018, 12, 28),
                            Publisher = "Beer Group",
                            Title = "Magnam"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Birdie Jacobi",
                            Genre = "Travel",
                            Language = "Papiamento",
                            PublicationDate = new DateOnly(2015, 8, 1),
                            Publisher = "Rowe - Aufderhar",
                            Title = "Doloribus voluptatem est"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Josephine Robel",
                            Genre = "Travel",
                            Language = "Slovak",
                            PublicationDate = new DateOnly(2021, 10, 12),
                            Publisher = "Ernser, Ryan and Veum",
                            Title = "Facilis eaque quis"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Freddy Bartoletti",
                            Genre = "Technology",
                            Language = "Romansh",
                            PublicationDate = new DateOnly(2016, 11, 21),
                            Publisher = "Dickinson, Walsh and Sanford",
                            Title = "Non"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Kaley Funk",
                            Genre = "Horror",
                            Language = "Lakota",
                            PublicationDate = new DateOnly(2022, 7, 21),
                            Publisher = "Gleason Group",
                            Title = "Repellat et eveniet"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Angelita Mante",
                            Genre = "History",
                            Language = "Bosnian",
                            PublicationDate = new DateOnly(2020, 9, 29),
                            Publisher = "Ferry Inc",
                            Title = "Inventore quia accusantium"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Kristin Bauch",
                            Genre = "Fantasy",
                            Language = "Ossetic",
                            PublicationDate = new DateOnly(2018, 5, 25),
                            Publisher = "Hudson Group",
                            Title = "Velit"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Magali Stokes",
                            Genre = "Thriller",
                            Language = "Volapük",
                            PublicationDate = new DateOnly(2018, 4, 28),
                            Publisher = "Gottlieb - Feeney",
                            Title = "Consectetur possimus eius"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Don Huel",
                            Genre = "Biography",
                            Language = "Tamil",
                            PublicationDate = new DateOnly(2019, 3, 5),
                            Publisher = "Gerlach, Reichel and Carroll",
                            Title = "Consequatur"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Rebecca Maggio",
                            Genre = "Horror",
                            Language = "Odia",
                            PublicationDate = new DateOnly(2015, 6, 2),
                            Publisher = "Kunze Inc",
                            Title = "Aut quaerat natus"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Tremaine Harber",
                            Genre = "Romance",
                            Language = "Xitsonga",
                            PublicationDate = new DateOnly(2015, 1, 20),
                            Publisher = "Rutherford Inc",
                            Title = "Repudiandae non"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Clovis Macejkovic",
                            Genre = "Mystery",
                            Language = "Persian",
                            PublicationDate = new DateOnly(2019, 3, 3),
                            Publisher = "Grimes - Harvey",
                            Title = "Fugit"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Elinor Emmerich",
                            Genre = "Mystery",
                            Language = "Romanian",
                            PublicationDate = new DateOnly(2017, 1, 6),
                            Publisher = "Bernier LLC",
                            Title = "Molestias"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Alexandria Hamill",
                            Genre = "Travel",
                            Language = "Kyrgyz",
                            PublicationDate = new DateOnly(2018, 9, 18),
                            Publisher = "Konopelski Inc",
                            Title = "Optio a"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Maeve Mitchell",
                            Genre = "Thriller",
                            Language = "Kyrgyz",
                            PublicationDate = new DateOnly(2019, 1, 7),
                            Publisher = "Reynolds - Schuster",
                            Title = "Facere perferendis"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Magdalen Upton",
                            Genre = "Travel",
                            Language = "Hawaiian",
                            PublicationDate = new DateOnly(2017, 8, 30),
                            Publisher = "Towne, Lueilwitz and Goodwin",
                            Title = "Nihil"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Santiago Bechtelar",
                            Genre = "Biography",
                            Language = "Arabic",
                            PublicationDate = new DateOnly(2015, 7, 14),
                            Publisher = "Kertzmann and Sons",
                            Title = "Non maiores"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Manuela Pagac",
                            Genre = "Autobiography",
                            Language = "Arabic",
                            PublicationDate = new DateOnly(2017, 1, 14),
                            Publisher = "Grimes Inc",
                            Title = "Suscipit"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Rylan Ruecker",
                            Genre = "Dystopian",
                            Language = "Uyghur",
                            PublicationDate = new DateOnly(2019, 9, 5),
                            Publisher = "Fisher Group",
                            Title = "Voluptatibus"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Terrell Schmeler",
                            Genre = "Biography",
                            Language = "Pashto",
                            PublicationDate = new DateOnly(2019, 2, 8),
                            Publisher = "Mueller - Lueilwitz",
                            Title = "Voluptatem"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Annamarie Schoen",
                            Genre = "Humor",
                            Language = "Maithili",
                            PublicationDate = new DateOnly(2014, 6, 2),
                            Publisher = "O'Reilly - Wilkinson",
                            Title = "Neque voluptatem"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Deon Bartell",
                            Genre = "Romance",
                            Language = "Bemba",
                            PublicationDate = new DateOnly(2014, 10, 22),
                            Publisher = "Williamson and Sons",
                            Title = "Ipsa"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Rocio Veum",
                            Genre = "Dystopian",
                            Language = "Divehi",
                            PublicationDate = new DateOnly(2021, 11, 21),
                            Publisher = "Ernser, Predovic and Beier",
                            Title = "Molestiae consequatur"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Ian Muller",
                            Genre = "Romance",
                            Language = "Chechen",
                            PublicationDate = new DateOnly(2016, 3, 11),
                            Publisher = "Kuphal - Nikolaus",
                            Title = "Ad"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Percival Hyatt",
                            Genre = "Thriller",
                            Language = "Estonian",
                            PublicationDate = new DateOnly(2016, 9, 9),
                            Publisher = "Gutmann - Murray",
                            Title = "Et"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Brooke Streich",
                            Genre = "Fantasy",
                            Language = "Interlingua",
                            PublicationDate = new DateOnly(2014, 2, 8),
                            Publisher = "Harber, Feil and Gerhold",
                            Title = "Commodi laboriosam ab"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Marguerite Lueilwitz",
                            Genre = "True Crime",
                            Language = "Wolaytta",
                            PublicationDate = new DateOnly(2017, 3, 25),
                            Publisher = "Mann - Greenfelder",
                            Title = "Ut"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Enid Will",
                            Genre = "Fantasy",
                            Language = "Sinhala",
                            PublicationDate = new DateOnly(2021, 11, 24),
                            Publisher = "Heller, Steuber and Bergnaum",
                            Title = "Rerum magnam"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Colin Hamill",
                            Genre = "Travel",
                            Language = "Basaa",
                            PublicationDate = new DateOnly(2021, 12, 15),
                            Publisher = "Mayer - Toy",
                            Title = "Voluptatem"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Cheyanne Brown",
                            Genre = "Romance",
                            Language = "Urdu",
                            PublicationDate = new DateOnly(2017, 5, 20),
                            Publisher = "Marvin - Wiza",
                            Title = "Quaerat porro"
                        },
                        new
                        {
                            Id = 41,
                            Author = "Yadira Welch",
                            Genre = "Dystopian",
                            Language = "Tatar",
                            PublicationDate = new DateOnly(2016, 10, 18),
                            Publisher = "Stoltenberg, Farrell and Wuckert",
                            Title = "Alias ea quod"
                        },
                        new
                        {
                            Id = 42,
                            Author = "Grayson Stehr",
                            Genre = "True Crime",
                            Language = "Tasawaq",
                            PublicationDate = new DateOnly(2019, 2, 13),
                            Publisher = "Friesen, Senger and Crist",
                            Title = "Totam"
                        },
                        new
                        {
                            Id = 43,
                            Author = "Florida Christiansen",
                            Genre = "Romance",
                            Language = "Soga",
                            PublicationDate = new DateOnly(2015, 5, 12),
                            Publisher = "Kilback - Cremin",
                            Title = "Similique"
                        },
                        new
                        {
                            Id = 44,
                            Author = "Tomas Pouros",
                            Genre = "Romance",
                            Language = "Bangla",
                            PublicationDate = new DateOnly(2018, 4, 25),
                            Publisher = "Armstrong, Osinski and O'Hara",
                            Title = "Hic impedit laudantium"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Clark Gaylord",
                            Genre = "Biography",
                            Language = "Akan",
                            PublicationDate = new DateOnly(2019, 2, 10),
                            Publisher = "Smitham, Baumbach and Kreiger",
                            Title = "Et dolorem"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Edythe Larkin",
                            Genre = "Mystery",
                            Language = "Croatian",
                            PublicationDate = new DateOnly(2015, 3, 16),
                            Publisher = "Hickle Inc",
                            Title = "Eius"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Caroline Blanda",
                            Genre = "Technology",
                            Language = "Filipino",
                            PublicationDate = new DateOnly(2017, 3, 27),
                            Publisher = "Bailey, Conroy and Mraz",
                            Title = "Accusamus dolorum"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Emmy Klocko",
                            Genre = "History",
                            Language = "Manipuri",
                            PublicationDate = new DateOnly(2023, 8, 11),
                            Publisher = "Streich - Baumbach",
                            Title = "Animi a voluptatem"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Shaniya Mitchell",
                            Genre = "Travel",
                            Language = "Kannada",
                            PublicationDate = new DateOnly(2022, 2, 20),
                            Publisher = "Ward Inc",
                            Title = "Sint"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Jace Hartmann",
                            Genre = "True Crime",
                            Language = "Duala",
                            PublicationDate = new DateOnly(2023, 8, 27),
                            Publisher = "Willms - Jacobi",
                            Title = "Ipsum rerum autem"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Jena Nader",
                            Genre = "Autobiography",
                            Language = "Tasawaq",
                            PublicationDate = new DateOnly(2022, 5, 4),
                            Publisher = "Gutkowski, Feil and Bednar",
                            Title = "Nam perspiciatis"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Devante Kulas",
                            Genre = "Thriller",
                            Language = "Amharic",
                            PublicationDate = new DateOnly(2021, 2, 9),
                            Publisher = "Zemlak - Bogan",
                            Title = "Totam"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Tabitha Kautzer",
                            Genre = "Fantasy",
                            Language = "Asu",
                            PublicationDate = new DateOnly(2020, 3, 1),
                            Publisher = "Zulauf, Schaefer and Kerluke",
                            Title = "Aperiam"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Lawrence Koch",
                            Genre = "Travel",
                            Language = "Gujarati",
                            PublicationDate = new DateOnly(2021, 3, 11),
                            Publisher = "Jenkins - Crist",
                            Title = "Nobis vel exercitationem"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Noble Bruen",
                            Genre = "Mystery",
                            Language = "Telugu",
                            PublicationDate = new DateOnly(2020, 5, 26),
                            Publisher = "Buckridge - Gislason",
                            Title = "Rerum illum"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Gage McClure",
                            Genre = "Dystopian",
                            Language = "Persian",
                            PublicationDate = new DateOnly(2022, 1, 20),
                            Publisher = "O'Hara, Lakin and Altenwerth",
                            Title = "Unde non ratione"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Berry Monahan",
                            Genre = "Horror",
                            Language = "Machame",
                            PublicationDate = new DateOnly(2014, 4, 21),
                            Publisher = "Veum, Kunde and Fadel",
                            Title = "A ut"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Marquise Kozey",
                            Genre = "Humor",
                            Language = "Vietnamese",
                            PublicationDate = new DateOnly(2021, 2, 26),
                            Publisher = "Hagenes LLC",
                            Title = "Dolor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
